# Generated by Django 5.2.5 on 2025-08-30 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='costo_compra',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='stock',
        ),
    ]
