# Generated by Django 5.2.5 on 2026-04-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_categoriaproducto_producto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='porcentaje_iva',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentaje de IVA del producto. Ej: 0, 5, 19', max_digits=5, verbose_name='IVA (%)'),
        ),
    ]
