# Generated by Django 5.2.5 on 2026-04-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='impuesto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='porcentaje_iva',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='IVA capturado al momento de la venta', max_digits=5),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='total_linea',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA_CREDITO', 'Tarjeta de Crédito'), ('TARJETA_DEBITO', 'Tarjeta de Débito'), ('TRANSFERENCIA', 'Transferencia')], default='EFECTIVO', max_length=20),
        ),
        migrations.AddField(
            model_name='venta',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Suma de precios base sin impuestos', max_digits=12),
        ),
        migrations.AddField(
            model_name='venta',
            name='total_impuestos',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Suma de todos los IVAs calculados por producto', max_digits=12),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='numero_documento',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha_hora',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='subtotal + total_impuestos', max_digits=12),
        ),
    ]
