# Generated by Django 5.2.5 on 2025-08-30 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0002_remove_producto_costo_compra_remove_producto_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaUbicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_lote', models.CharField(help_text='Código o número de remisión del proveedor', max_length=100, unique=True)),
                ('fecha_recepcion', models.DateTimeField(auto_now_add=True)),
                ('fecha_caducidad', models.DateField()),
                ('costo_compra_lote', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='inventario.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('tipo', models.CharField(choices=[('BODEGA', 'Bodega'), ('EST_BOD', 'Estante de Bodega'), ('EST_TDA', 'Estante de Tienda')], max_length=10)),
                ('capacidad_maxima', models.PositiveIntegerField(blank=True, help_text='Capacidad en unidades o volumen', null=True)),
                ('categoria', models.ForeignKey(blank=True, help_text='Categoría de productos permitidos en esta ubicación (ej: Refrigerados)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bodega.categoriaubicacion')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_ubicaciones', to='bodega.ubicacion')),
            ],
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='bodega.lote')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_items', to='bodega.ubicacion')),
            ],
            options={
                'unique_together': {('lote', 'ubicacion')},
            },
        ),
    ]
