# Generated by Django 5.2.5 on 2025-09-01 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AjusteInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_anterior', models.IntegerField()),
                ('cantidad_nueva', models.IntegerField()),
                ('diferencia', models.IntegerField(editable=False)),
                ('motivo', models.CharField(choices=[('CONTEO', 'Diferencia por Conteo Físico'), ('DAÑADO', 'Producto Dañado / Merma'), ('ROBO', 'Robo o Extravío'), ('RECEPCION', 'Error en Recepción'), ('OTRO', 'Otro')], max_length=10)),
                ('notas', models.TextField(blank=True)),
                ('fecha_ajuste', models.DateTimeField(auto_now_add=True)),
                ('stock_item', models.ForeignKey(help_text='Ítem de stock que se ajusta', on_delete=django.db.models.deletion.PROTECT, to='bodega.stockitem')),
                ('usuario', models.ForeignKey(help_text='Usuario que realiza el ajuste', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
