# Generated by Django 5.2.5 on 2026-02-26 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0002_ajusteinventario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lote',
            name='costo_compra_lote',
        ),
        migrations.AddField(
            model_name='lote',
            name='costo_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo Unitario'),
            preserve_default=False,
        ),
    ]
