# Generated by Django 5.2.5 on 2026-03-05 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0003_remove_lote_costo_compra_lote_lote_costo_unitario'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='cantidad_inicial',
            field=models.PositiveIntegerField(default=0, help_text='Cantidad total de unidades que llegaron en la factura de este lote'),
        ),
    ]
