# Generated by Django 5.2.5 on 2026-03-26 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0004_lote_cantidad_inicial'),
        ('inventario', '0003_categoriaproducto_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='inventario.producto'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_items', to='bodega.lote'),
        ),
    ]
