# Generated by Django 5.2.5 on 2026-05-04 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0005_alter_lote_producto_alter_stockitem_lote'),
        ('inventario', '0004_producto_porcentaje_iva'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='proveedor',
            field=models.ForeignKey(blank=True, help_text='Proveedor del que proviene este lote', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes', to='inventario.proveedor'),
        ),
    ]
