# Generated by Django 5.2.5 on 2026-05-08 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallerecepcion',
            name='fecha_caducidad',
            field=models.DateField(blank=True, help_text='Fecha de caducidad del lote recibido', null=True),
        ),
    ]
